site_name: uCore for LoongArch32 Tutorial Book
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: material/memory
nav:
  - 主页: index.md
  - 0：实验准备:
    - 关于实验: lab0/lab0.md
    - 准备知识: lab0/prepare.md
    - 环境配置: lab0/env.md
    - 裸机程序: lab0/bare-prog.md
    - 调试方法: lab0/debug.md
    - 实验任务: lab0/task.md
    - 参考: lab0/ref.md
  - 1：系统软件: 
    - 关于实验: lab1/lab1.md
    - 操作系统启动流程: lab1/booting.md
    - 内联汇编: lab1/inline_asm.md
    - 编译方法: lab1/compile.md
    - 实验任务: lab1/task.md
  - 2：物理内存:
    - 关于实验: lab2/lab2.md
    - 分页机制: lab2/paging.md
    - 编译方法: lab2/compile.md
    - 实验任务: lab2/task.md
  - 3：虚拟内存: 
    - 关于实验: lab3/lab3.md
    - 虚拟内存: lab3/vmm.md
    - 编译方法: lab3/compile.md
    - 实验任务: lab3/task.md
  - 4：内核线程: 
    - 关于实验: lab4/lab4.md
    - 内核线程: lab4/kthread.md
    - 编译方法: lab4/compile.md
    - 实验任务: lab4/task.md
    - 附录: lab4/appendix.md
  - 5：用户进程:
    - 关于实验: lab5/lab5.md
    - 进程管理: lab5/process.md
    - 编译方法: lab5/compile.md
    - 实验任务: lab5/task.md
    - 附录: lab5/appendix.md
  - 6：调度器:
    - 关于实验: lab6/lab6.md
    - 进程调度实现: lab6/sche_impl.md
    - 调度器框架: lab6/framework.md
    - Stride Scheduling: lab6/stride.md
    - 编译方法: lab6/compile.md
    - 实验任务: lab6/task.md
  - 7：同步互斥: lab7/lab7.md
  - 8：文件系统: lab8/lab8.md
  - Chiplab: chiplab/chiplab.md

plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_name: 'ucore_la32_docs'
repo_url: 'https://github.com/cyyself/ucore_la32_docs'